### PR TITLE
(fix): Changed PreventExecFrpolicy from file to process

### LINKED ISSUE #205: Intent preventExecutionFromTempOrLogsFolders having issue with listing of directories
When the preventExecutionFromTempOrLogsFolders intent is applied, I am unable to view the tmp folder:

~ # ls /tmp/
ls: can't open '/tmp/': Permission denied
~ # cp wget /tmp/
cp: can't stat 'wget': No such file or directory
~ # cp /bin/wget /tmp/
cp: can't create '/tmp/wget': Permission denied

This is due the fact that the kubearmor policy generated is a file policy, not a process policy.

Once the kubearmor policy is changed to  a process policy:

/ # ls /tmp/
/ # cp /bin/wget /tmp/

/ # /tmp/wget www.google.com
sh: /tmp/wget: Permission denied

### PR DESCRIPTION
**Pull request by VedRatan**
## Description

Fixes #205
**Does this PR introduce a breaking change?**

## Checklist

- [x] PR title follows the `<type>: <description>` convention
- [ ] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
- [ ] I have updated the [documentation](../docs) accordingly
- [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
- [ ] I have performed a self-review of my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: pkg/adapter/nimbus-kubearmor/processor/kspbuilder.go [hunk 1]
```diff
@@ -268,31 +268,25 @@ func disallowChRoot() kubearmorv1.KubeArmorPolicy {
 func disallowBinaries() kubearmorv1.KubeArmorPolicy { // ref: https://www.tenable.com/audits/items/search?q=noexec&sort=&page=1
 	return kubearmorv1.KubeArmorPolicy{
 		Spec: kubearmorv1.KubeArmorPolicySpec{
-			File: kubearmorv1.FileType{
-				MatchDirectories: []kubearmorv1.FileDirectoryType{
+			Process: kubearmorv1.ProcessType{
+				MatchPaths: []kubearmorv1.ProcessPathType{
 					{
-						Directory: "/var/tmp/",
-						Recursive: true,
```
Comment (shivaccuknox) [inline pkg/adapter/nimbus-kubearmor/processor/kspbuilder.go:275]: The recursive option can be applied for process policies also. Please check the example on 

https://docs.kubearmor.io/kubearmor/documentation/security_policy_examples

**Review by shivaccuknox — COMMENTED** [review]
Also please provide the corresponding e2e test case.

File: pkg/adapter/nimbus-kubearmor/processor/kspbuilder.go (hunk 1 above)
Comment (VedRatan) [reply pkg/adapter/nimbus-kubearmor/processor/kspbuilder.go:275]: done @shivaccuknox

**Review by shivaccuknox — APPROVED** [review]
